import = ["/home/stefan/.config/alacritty/dracula.toml"]

[scrolling]
history = 100000

[window]
opacity = 0.94
startup_mode = "Fullscreen"

[font]
size = 12.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"
